
CRON:
  FormBuilder:
    Email:
      layoutRootPath: 'resource://CRON.FormBuilder/Private/Templates/Email/Layouts'
      templatePathAndFilenameFormat: 'resource://CRON.FormBuilder/Private/Templates/Email/%s.txt'
      defaults:
        from: dev@cron.eu
        subject: 'New Message from FormBuilder'
    Controller:
      useForward: true
    View:
      useRequiredAttribute: true
    Upload:
      maxFileSize: 10000000
      allowedMimeTypes:
        - application/pdf
        - image/bmp
        - image/jpeg
        - image/png
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          CRON.FormBuilder:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        CRON.FormBuilder: true
  Fusion:
    defaultContext:
      'CRON.TimeHash': 'CRON\FormBuilder\Eel\Helper\TimeHashHelper'
